### PR TITLE
Allow for hidden integration tests

### PR DESCRIPTION
**Pull request by laurelmay**
This implements hidden integration tests using the `_H` suffix as described in #3. `bash`'s extended globbing is used to copy files that *don't* contain in `_H.` The `.` allows for checking that the `_H` is at the end of the test name, right before the file extension (otherwise `A_Hello_World` would be a hidden test).

This should not introduce any student-viewable complexity for hidden integration tests in the distribution files (since they are guarded by `BEGIN_SOLUTION/END_SOLUTION` in the `itests.include` file.

### CODE REVIEW

**Comment by laurelmay** [comment]
If there is a preference for using a separate folder or .include file for integration tests, I am happy to try to put something together. This just seemed like the simplest option to implement

**Comment by lam2mo** [comment]
I agree this looks pretty clean and simple. Have you done any looking to see how standard the extended globbing feature is across platforms and various versions of Bash?

**Comment by laurelmay** [comment]
My understanding is that `extglob` is fairly standard in bash (it would not be available in `sh`). Testing on macOS with bash 3.2.57(1) and on Linux with 4.4.12(1), it seems to work fine. http://wiki-dev.bash-hackers.org/syntax/pattern#bugs_and_portability_considerations suggests that `extglob` should be fairly standard as it is compatible with ksh88.

**Comment by lam2mo** [comment]
Sounds good to me. Thanks!

This closes #3.

**Pull request merged**
